
services:
  backend:
    image: inttype/solsol:backend-latest
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - ./apps/backend/.env
    environment:
      # 포트/프로필/SQL init
      SERVER_PORT: ${SERVER_PORT:-8080}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE:-never}

      # RDS 접속
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${RDS_USER}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}

      TZ: Asia/Seoul
      JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose: ["8080"]
    networks: [solsol-net]

  user-web:
    image: inttype/solsol:user-web-latest
    build:
      context: ./apps/frontend/User
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose: ["80"]
    networks: [solsol-net]

  admin-web:
    image: inttype/solsol:admin-web-latest
    build:
      context: ./apps/frontend/Admin
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose: ["80"]
    networks: [solsol-net]

  gateway:
    image: nginx:alpine
    depends_on: [backend, user-web, admin-web]
    ports: 
        - "80:80"
        - "443:443" 
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - /letsencrypt:/etc/letsencrypt    
      - /certbot:/var/www/certbot          
      - /logs:/var/log/nginx 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TZ: Asia/Seoul
    networks: [solsol-net]

networks:
  solsol-net:
    driver: bridge
