spring:
  application:
    name: heycalendar
  
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/heycalendar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:heycalendar}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA/Hibernate configuration (if needed alongside MyBatis)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
# MyBatis configuration
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.solsol.heycalendar.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    default-executor-type: simple
    default-statement-timeout: 25
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Logging configuration
logging:
  level:
    com.solsol.heycalendar: DEBUG
    com.solsol.heycalendar.mapper: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized